/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDrillRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GAME_ROLE"
      | "MANAGER_ROLE"
      | "getActiveGames"
      | "getGameAt"
      | "getGameCount"
      | "isAuthorized"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameProposed"
      | "GameRegistered"
      | "GameUnregistered"
      | "GameVoted"
      | "ManagerFired"
      | "ManagerHired"
  ): EventFragment;

  encodeFunctionData(functionFragment: "GAME_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveGames",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGameAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "GAME_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGameAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
}

export namespace GameProposedEvent {
  export type InputTuple = [
    gameContract: AddressLike,
    proposer: AddressLike,
    isAdding: boolean
  ];
  export type OutputTuple = [
    gameContract: string,
    proposer: string,
    isAdding: boolean
  ];
  export interface OutputObject {
    gameContract: string;
    proposer: string;
    isAdding: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameRegisteredEvent {
  export type InputTuple = [gameContract: AddressLike];
  export type OutputTuple = [gameContract: string];
  export interface OutputObject {
    gameContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameUnregisteredEvent {
  export type InputTuple = [gameContract: AddressLike];
  export type OutputTuple = [gameContract: string];
  export interface OutputObject {
    gameContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameVotedEvent {
  export type InputTuple = [
    gameContract: AddressLike,
    voter: AddressLike,
    currentVotes: BigNumberish,
    neededVotes: BigNumberish
  ];
  export type OutputTuple = [
    gameContract: string,
    voter: string,
    currentVotes: bigint,
    neededVotes: bigint
  ];
  export interface OutputObject {
    gameContract: string;
    voter: string;
    currentVotes: bigint;
    neededVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerFiredEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerHiredEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDrillRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDrillRegistry;
  waitForDeployment(): Promise<this>;

  interface: IDrillRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GAME_ROLE: TypedContractMethod<[], [string], "view">;

  MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  getActiveGames: TypedContractMethod<[], [string[]], "view">;

  getGameAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getGameCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorized: TypedContractMethod<
    [_who: AddressLike, _role: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GAME_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveGames"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGameAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getGameCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorized"
  ): TypedContractMethod<
    [_who: AddressLike, _role: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "GameProposed"
  ): TypedContractEvent<
    GameProposedEvent.InputTuple,
    GameProposedEvent.OutputTuple,
    GameProposedEvent.OutputObject
  >;
  getEvent(
    key: "GameRegistered"
  ): TypedContractEvent<
    GameRegisteredEvent.InputTuple,
    GameRegisteredEvent.OutputTuple,
    GameRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "GameUnregistered"
  ): TypedContractEvent<
    GameUnregisteredEvent.InputTuple,
    GameUnregisteredEvent.OutputTuple,
    GameUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "GameVoted"
  ): TypedContractEvent<
    GameVotedEvent.InputTuple,
    GameVotedEvent.OutputTuple,
    GameVotedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerFired"
  ): TypedContractEvent<
    ManagerFiredEvent.InputTuple,
    ManagerFiredEvent.OutputTuple,
    ManagerFiredEvent.OutputObject
  >;
  getEvent(
    key: "ManagerHired"
  ): TypedContractEvent<
    ManagerHiredEvent.InputTuple,
    ManagerHiredEvent.OutputTuple,
    ManagerHiredEvent.OutputObject
  >;

  filters: {
    "GameProposed(address,address,bool)": TypedContractEvent<
      GameProposedEvent.InputTuple,
      GameProposedEvent.OutputTuple,
      GameProposedEvent.OutputObject
    >;
    GameProposed: TypedContractEvent<
      GameProposedEvent.InputTuple,
      GameProposedEvent.OutputTuple,
      GameProposedEvent.OutputObject
    >;

    "GameRegistered(address)": TypedContractEvent<
      GameRegisteredEvent.InputTuple,
      GameRegisteredEvent.OutputTuple,
      GameRegisteredEvent.OutputObject
    >;
    GameRegistered: TypedContractEvent<
      GameRegisteredEvent.InputTuple,
      GameRegisteredEvent.OutputTuple,
      GameRegisteredEvent.OutputObject
    >;

    "GameUnregistered(address)": TypedContractEvent<
      GameUnregisteredEvent.InputTuple,
      GameUnregisteredEvent.OutputTuple,
      GameUnregisteredEvent.OutputObject
    >;
    GameUnregistered: TypedContractEvent<
      GameUnregisteredEvent.InputTuple,
      GameUnregisteredEvent.OutputTuple,
      GameUnregisteredEvent.OutputObject
    >;

    "GameVoted(address,address,uint256,uint256)": TypedContractEvent<
      GameVotedEvent.InputTuple,
      GameVotedEvent.OutputTuple,
      GameVotedEvent.OutputObject
    >;
    GameVoted: TypedContractEvent<
      GameVotedEvent.InputTuple,
      GameVotedEvent.OutputTuple,
      GameVotedEvent.OutputObject
    >;

    "ManagerFired(address)": TypedContractEvent<
      ManagerFiredEvent.InputTuple,
      ManagerFiredEvent.OutputTuple,
      ManagerFiredEvent.OutputObject
    >;
    ManagerFired: TypedContractEvent<
      ManagerFiredEvent.InputTuple,
      ManagerFiredEvent.OutputTuple,
      ManagerFiredEvent.OutputObject
    >;

    "ManagerHired(address)": TypedContractEvent<
      ManagerHiredEvent.InputTuple,
      ManagerHiredEvent.OutputTuple,
      ManagerHiredEvent.OutputObject
    >;
    ManagerHired: TypedContractEvent<
      ManagerHiredEvent.InputTuple,
      ManagerHiredEvent.OutputTuple,
      ManagerHiredEvent.OutputObject
    >;
  };
}
