/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DrillRegistry } from "./DrillRegistry";
export type { DrillStorage } from "./DrillStorage";
export type { DrillToken } from "./DrillToken";
